resource "local_file" "ethereum_config" {
  filename = "/home/saltylighter/terraform-practice/ethereum.conf"
  content  = <<-EOT
    # Ethereum Node Config
    # Generated by Terraform
    
    network=holesky
    jwt_path=/secrets/jwt.hex
    rpc_port=8545
    engine_port=8551
    p2p_port=30303
  EOT
}
